name: Coverage

on: [push]

env:
  FORCE_COLOR: 1

jobs:
  ubuntu-focal:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: sudo apt-get install -y bash kcov
      - name: Install Shellspec 
        run: |
          curl -fsSL https://git.io/shellspec | sh -s -- -y
          sudo ln -s ${HOME}/.local/lib/shellspec/shellspec /usr/local/bin/shellspec
          ls -la ${HOME}/.local/lib/shellspec
          echo "shellspec symlink:"
          ls -la /usr/local/bin/shellspec
          /usr/local/bin/shellspec --version
          which shellspec
          shellspec --version
      - name: Install bpkg and dependencies
        run: |         
          curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/master/setup.sh" | bash
          bpkg getdeps
      - name: Install cc-test-reporter
        env:
          CC_TEST_REPORTER_URL: https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
        run: |
          curl -sSL "$CC_TEST_REPORTER_URL" > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Run shellspec and upload coverage (Coveralls)
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          shellspec --shell bash --kcov --kcov-options "--coveralls-id=${COVERALLS_REPO_TOKEN}"