name: Coverage

on: [push]

env:
  FORCE_COLOR: 1

jobs:
  ubuntu-focal:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: sudo apt-get install -y bash kcov
      - name: Run shellspec and upload coverage (Coveralls)
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          sudo ./shellspec --task fixture:stat:prepare
          ./shellspec --shell bash --kcov --kcov-options "--coveralls-id=${COVERALLS_REPO_TOKEN}"