name: Ubuntu Focal Fossa

on: [push, pull_request]

env:
  FORCE_COLOR: 1

jobs:
  ubuntu-focal:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        shells:
          - {shell: bash,        package: bash}
      fail-fast: false
    steps:      
      - run: sudo apt-get install -y ${{ matrix.shells.package }}
      - name: Install Shellspec - non-windows
        if: ${{ matrix.os != 'windows' }}
        run: |
          curl -fsSL https://git.io/shellspec | sh -s -- -y
          sudo ln -s ${HOME}/.local/lib/shellspec/shellspec /usr/local/bin/shellspec
          ls -la ${HOME}/.local/lib/shellspec
          echo "shellspec symlink:"
          ls -la /usr/local/bin/shellspec
          /usr/local/bin/shellspec --version
          which shellspec
          shellspec --version
      - uses: actions/checkout@v2
      - run: SH="${{ matrix.shells.shell }}" shellspec
